model:
  model_id: diff_dec
  sample_size: [360, 640]
  channels: 3
  latent_size: 4
  latent_channels: 128
  patch_size: 32

  n_layers: 24
  n_heads: 24
  d_model: 1152

  causal: false
  mimetic_init: false

train:
  trainer_id: diff_dec
  data_id: s3_cod

  target_batch_size: 256
  batch_size: 32

  epochs: 200

  #opt: AdamW
  #  opt_kwargs:
  #  lr: 1.0e-4
  #  eps: 1.0e-15
  #  betas: [0.9, 0.95]
  #  weight_decay: 1.0e-4
  opt: Muon
  opt_kwargs:
    lr: 1.0e-3
    momentum: 0.95
    adamw_lr: 1.0e-4
    adamw_wd: 0.01
    adamw_eps: 1.0e-15
    adamw_betas: [0.9, 0.95]
    adamw_keys:
      [core.conv_in, core.conv_out, core.proj_in, core.proj_out]

  delay_adv: 0
  warmup_adv: 500

  scheduler: null

  checkpoint_dir: checkpoints/diffdec

  sample_interval: 1000
  save_interval: 10000

  teacher_ckpt: checkpoints/cod_128x_huge/500m_cod128x_50k_ema.pt
  teacher_cfg: configs/cod_128x_huge_kl.yml

  latent_scale: 1.0

wandb:
  name: ${env:WANDB_USER_NAME}
  project: new_vaes
  run_name: v0
