model:
  model_id: tekken_rft_v2
  sample_size: [14, 23]
  channels: 128
  n_buttons: 8
  n_layers: 16
  n_heads: 16
  d_model: 2048

  n_frames: 1024
  has_audio: false

  cfg_prob: 0.0
  causal: true
  uncond: false
  backbone: dit

  local_window: 16
  global_window: 128  # full window

train:
  trainer_id: tekken_dmd
  data_id: tekken_multi
  data_kwargs:
    window_length: 128
    temporal_compression: 1
    root_dir: /mnt/data/laplace/owl-wms/preproccessing/cached_dcae_fix/train

  sample_data_id: tekken_multi
  sample_data_kwargs:
    window_length: 120  # size of single ground truth start tokens
    temporal_compression: 1
    root_dir: /mnt/data/laplace/owl-wms/preproccessing/cached_dcae_fix/val

  target_batch_size: 8
  batch_size: 1

  epochs: 10000

  opt: Muon
  opt_kwargs:
    lr: 1.0e-3
    momentum: 0.95
    adamw_lr: 1.0e-4
    adamw_wd: 1.0e-4
    adamw_eps: 1.0e-15
    adamw_betas: [0.9, 0.95]
    adamw_keys: [core.proj_in, core.proj_out.proj, core.t_embed, core.action_embed, gate, adaln]   

  scheduler: null

  checkpoint_dir: /mnt/data/owl-wms/checkpoints/tekken_pose_dmd
  output_path: /mnt/data/owl-wms/checkpoints/tekken_pose_dmd_ema
  resume_ckpt: null

  teacher_cfg: configs/dit_v4.yml
  teacher_ckpt: /mnt/data/lapp0/checkpoints/89220499/checkpoints/step_170000.pt
  student_ckpt: /mnt/data/lapp0/checkpoints/89220499/checkpoints/step_170000.pt

  sample_interval: 2500
  save_interval: 5000

  sampler_id: t3_action_caching
  sampler_kwargs:
    n_steps: 32
    #window_length: 16
    cfg_scale: 1.0
    num_frames: 192
    noise_prev: 0.2
    custom_schedule: [1.0, 0.75, 0.5, 0.25]

  n_samples: 4
  eval_sample_dir: null

  vae_id: null
  vae_batch_size: 4

  vae_scale: 1.0 #0.63
  vae_cfg_path: "preproccessing/checkpoints/tekken_vae_H200_v6/config.yaml" #null # Path to your VAE config
  vae_ckpt_path: "/mnt/data/laplace/owl-wms/preproccessing/checkpoints/tekken_vae_H200_v6/step_48000.pt" # Path to your VAE checkpoint

  update_ratio: 5
  ts_shift: 8
  rollout_steps: 4
  log_predictions: false
  regression_weight: 0.0

wandb:
  name: shahbuland  # lapp0-andrew-lapp
  project: video_models  # owl
  run_name: causvid_dit_v4
