model:
  model_id: game_rft
  sample_size: 8
  channels: 128

  n_layers: 8
  n_heads: 24
  d_model: 1536

  tokens_per_frame: 64
  n_buttons: 11
  n_mouse_axes: 2

  cfg_prob: 0.0
  n_frames: 1536
  local_idx: 2

  causal: true
  uncond: false
  backbone: dit
  has_audio: false
  rope_impl: motion
  rope_ats_delta: 2.0

  local_window: 16
  global_window: null  # full window

train:
  trainer_id: ode_distill_vid
  data_id: cod
  data_kwargs:
    window_length: 60
    dataset_path: /mnt/data/lapp0/BlackOpsColdWar/train_npy
    batch_columns: ["depth_latent", "mouse", "buttons"]

  sample_data_id: cod
  sample_data_kwargs:
    window_length: 60  # size of single ground truth start tokens
    dataset_path: /mnt/data/lapp0/BlackOpsColdWar/train_npy
    batch_columns: ["depth_latent", "mouse", "buttons"]

  target_batch_size: 64
  batch_size: 8

  epochs: 10000

  opt: Muon
  opt_kwargs:
    lr: 1.0e-3
    momentum: 0.95
    adamw_lr: 1.0e-4
    adamw_wd: 1.0e-4
    adamw_eps: 1.0e-15
    adamw_betas: [0.9, 0.95]
    adamw_keys: [proj_in, proj_out.proj, t_embed, control_embed, gate, adaln]
    

  scheduler: null

  checkpoint_dir: checkpoints/video_dit_v4_prune
  output_path: /mnt/data/owl-wms/checkpoints/dit_v4_prune
  resume_ckpt: null

  teacher_cfg: configs/dit_v4.yml
  teacher_ckpt: /mnt/data/lapp0/checkpoints/89220499/checkpoints/step_170000.pt
  student_ckpt: /mnt/data/lapp0/checkpoints/89220499/checkpoints/step_170000.pt

  sample_interval: 50
  save_interval: 10000

  sampler_id: av_caching
  sampler_kwargs:
    n_steps: 16
    #window_length: 16
    cfg_scale: 1.0
    num_frames: 120
    noise_prev: 0.2

  n_samples: 4
  eval_sample_dir: null

  vae_id: null
  vae_batch_size: 4

  vae_scale: 0.63
  vae_cfg_path: /mnt/data/shahbuland/owl-vaes/configs/cod_yt_v2/base.yml
  vae_ckpt_path: /mnt/data/checkpoints/owl_vaes/cod_yt_v2/cod_yt_v2_515k_ema_decoder.pt

  rollout_steps: 16
  subsample: 0.25
  cfg_scale: 1.5
  gen_p: 0.25

wandb:
  name: shahbuland  # lapp0-andrew-lapp
  project: video_models  # owl
  run_name: prune_dit_v4